package com.example.trackingapp;

import android.app.*;import android.os.*;import android.database.sqlite.SQLiteDatabase;import android.text.InputType;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.content.*;import android.widget.*;import java.text.*;import java.util.*;import org.json.*;

public class MainActivity extends Activity{
 TrackingDatabase db; LinearLayout root; int blue=0xff2f6fed; Handler handler=new Handler(); Map<String,Long> timers=new HashMap<>();
 public void onCreate(Bundle b){super.onCreate(b);db=new TrackingDatabase(this);showHome(0);} TextView tv(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setPadding(16,12,16,8);return v;} Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;} void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);setContentView(root);} 
 void showHome(int tab){base();LinearLayout tabs=new LinearLayout(this);tabs.setWeightSum(2);Button s=btn("Sessions"),t=btn("Tracker");tabs.addView(s,new LinearLayout.LayoutParams(0,-2,1));tabs.addView(t,new LinearLayout.LayoutParams(0,-2,1));root.addView(tabs);FrameLayout body=new FrameLayout(this);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));s.setOnClickListener(v->showHome(0));t.setOnClickListener(v->showHome(1)); if(tab==0)sessions(body);else trackers(body);} 
 void sessions(FrameLayout body){ScrollView sc=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);sc.addView(box);Button add=btn("Neue Session starten");box.addView(add);add.setOnClickListener(v->chooseTracker());for(Session se:db.sessions()){Tracker tr=db.readTracker(se.trackerId);int count=db.recordCount(se.id);TextView card=tv(tr.name+"\n"+date(se.createdAt)+" · "+se.status+" · "+count+"/"+tr.items.size()+" Items\n"+preview(se.id),18);card.setBackgroundColor(0xfff2f4f8);card.setOnClickListener(v->openSession(se.id));box.addView(card,new LinearLayout.LayoutParams(-1,-2));}body.addView(sc);} 
 String preview(long sid){StringBuilder b=new StringBuilder();for(ItemRecord r:db.records(sid).values()){if(b.length()>0)b.append(" | ");b.append(r.valuesJson);if(b.length()>90)break;}return b.toString();} String date(long ms){return new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.US).format(new Date(ms));}
 void chooseTracker(){List<Tracker> ts=db.trackers();String[] names=new String[ts.size()];for(int i=0;i<ts.size();i++)names[i]=ts.get(i).name;new AlertDialog.Builder(this).setTitle("Tracker auswählen").setItems(names,(d,which)->openSession(db.createSession(ts.get(which).id))).show();}
 void trackers(FrameLayout body){ScrollView sc=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);sc.addView(box);for(Tracker tr:db.trackers()){int fields=0;for(Item it:tr.items)fields+=it.fields.size();TextView card=tv(tr.name+"\n"+tr.items.size()+" Items · "+fields+" Fields",18);card.setBackgroundColor(0xfff2f4f8);card.setOnClickListener(v->editTracker(tr.id));box.addView(card);}body.addView(sc);} 
 void editTracker(long id){Tracker tr=db.readTracker(id);base();Button back=btn("Zurück");root.addView(back);back.setOnClickListener(v->showHome(1));EditText editor=new EditText(this);editor.setText(JsonUtil.trackerToJson(tr));editor.setGravity(Gravity.TOP);editor.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);root.addView(editor,new LinearLayout.LayoutParams(-1,0,1));Button save=btn("Tracker speichern");root.addView(save);save.setOnClickListener(v->{try{saveTracker(id,editor.getText().toString());Toast.makeText(this,"Gespeichert",0).show();showHome(1);}catch(Exception e){Toast.makeText(this,e.getMessage(),1).show();}});} 
 void saveTracker(long id,String json){SQLiteDatabaseHack.updateTracker(db,id,json);} 
 void openSession(long sid){Session se=db.session(sid);Tracker tr=db.readTracker(se.trackerId);Map<Long,ItemRecord> rec=db.records(sid);int start=0;for(int i=0;i<tr.items.size();i++)if(!rec.containsKey(tr.items.get(i).id)){start=i;break;}showItem(se,tr,start);} 
 void showItem(Session se,Tracker tr,int idx){base();boolean ro="completed".equals(se.status);Item item=tr.items.get(idx);root.addView(tv(tr.name+" · "+se.status+"\nItem "+(idx+1)+"/"+tr.items.size()+": "+item.title,20));ScrollView sc=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);sc.addView(box);Map<String,Object> values=initialValues(se,item);Map<String,View> inputs=new HashMap<>();for(FieldDefinition f:item.fields)fieldControl(box,f,values,inputs,ro);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=new LinearLayout(this);nav.setWeightSum(3);Button prev=btn("Zurück"), next=btn(ro?"Weiter":"Speichern & weiter"), close=btn(ro?"Übersicht":"Session speichern / schließen");nav.addView(prev,new LinearLayout.LayoutParams(0,-2,1));nav.addView(next,new LinearLayout.LayoutParams(0,-2,1));nav.addView(close,new LinearLayout.LayoutParams(0,-2,1));root.addView(nav);prev.setOnClickListener(v->{if(idx>0)showItem(se,tr,idx-1);else showHome(0);});next.setOnClickListener(v->{if(!ro)db.saveRecord(se,item.id,readInputs(item,inputs));if(idx<tr.items.size()-1)showItem(db.session(se.id),tr,idx+1);else Toast.makeText(this,"Letztes Item erreicht",0).show();});close.setOnClickListener(v->{if(!ro){db.saveRecord(se,item.id,readInputs(item,inputs));db.complete(se.id);}showHome(0);});}
 Map<String,Object> initialValues(Session se,Item item){Map<Long,ItemRecord> rs=db.records(se.id);if(rs.containsKey(item.id))return JsonUtil.toMap(rs.get(item.id).valuesJson);Map<String,Object> m=new LinkedHashMap<>();for(FieldDefinition f:item.fields){Object val=TrackingDatabase.NO_PREVIOUS;if(f.prefillFromPrevious)val=db.previousValue(se.trackerId,se.id,item.id,f.key);if(!f.prefillFromPrevious||val==TrackingDatabase.NO_PREVIOUS)val=parse(f.defaultValue,f.type);m.put(f.key,val);}return m;} Object parse(String s,String type){if(s==null||s.isEmpty())return null;try{if("int".equals(type)||"duration".equals(type))return Long.parseLong(s);if("float".equals(type))return Double.parseDouble(s);}catch(Exception ignored){}return s;}
 void fieldControl(LinearLayout box,FieldDefinition f,Map<String,Object> vals,Map<String,View> inputs,boolean ro){box.addView(tv(f.label+(f.unit==null||f.unit.isEmpty()?"":" ("+f.unit+")"),16));Object val=vals.get(f.key);if("string".equals(f.type)){EditText e=new EditText(this);e.setText(val==null?"":String.valueOf(val));e.setEnabled(!ro);box.addView(e);inputs.put(f.key,e);return;}if("duration".equals(f.type)){TextView display=tv(formatMs(toLong(val)),24);display.setTag(toLong(val));LinearLayout row=new LinearLayout(this);Button start=btn("Start"),stop=btn("Stop"),reset=btn("Reset");row.addView(start);row.addView(stop);row.addView(reset);box.addView(display);box.addView(row);start.setEnabled(!ro);stop.setEnabled(!ro);reset.setEnabled(!ro);start.setOnClickListener(v->{timers.put(f.key,System.currentTimeMillis()-((Long)display.getTag()));tick(display,f.key);});stop.setOnClickListener(v->timers.remove(f.key));reset.setOnClickListener(v->{timers.remove(f.key);display.setTag(0L);display.setText(formatMs(0));});inputs.put(f.key,display);return;}LinearLayout row=new LinearLayout(this);Button minus=btn("−"),plus=btn("+");EditText e=new EditText(this);e.setText(val==null?"":String.valueOf(val));e.setInputType("int".equals(f.type)?InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_SIGNED:InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL|InputType.TYPE_NUMBER_FLAG_SIGNED);e.setEnabled(!ro);minus.setEnabled(!ro);plus.setEnabled(!ro);View.OnClickListener adj=v->{hideKeyboard(e);double cur=e.getText().toString().isEmpty()?0:Double.parseDouble(e.getText().toString());cur+=v==plus?f.increment:-f.increment;e.setText("int".equals(f.type)?String.valueOf(Math.round(cur)):String.format(Locale.US,"%."+f.decimals+"f",cur));};minus.setOnClickListener(adj);plus.setOnClickListener(adj);row.addView(minus);row.addView(e,new LinearLayout.LayoutParams(0,-2,1));row.addView(plus);box.addView(row);inputs.put(f.key,e);} 
 void tick(TextView d,String key){if(!timers.containsKey(key))return;long ms=System.currentTimeMillis()-timers.get(key);d.setTag(ms);d.setText(formatMs(ms));handler.postDelayed(()->tick(d,key),500);} void hideKeyboard(View v){((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(v.getWindowToken(),0);v.clearFocus();}
 Map<String,Object> readInputs(Item item,Map<String,View> ins){Map<String,Object> m=new LinkedHashMap<>();for(FieldDefinition f:item.fields){View v=ins.get(f.key);if(v instanceof EditText){String s=((EditText)v).getText().toString();m.put(f.key,parse(s,f.type));}else if(v instanceof TextView)m.put(f.key,(Long)v.getTag());}return m;} long toLong(Object o){if(o instanceof Number)return ((Number)o).longValue();try{return Long.parseLong(String.valueOf(o));}catch(Exception e){return 0;}}String formatMs(long ms){long sec=ms/1000;return String.format(Locale.US,"%02d:%02d:%02d",sec/3600,(sec/60)%60,sec%60);} 
}
