package com.example.trackingapp;

import android.content.*;import android.database.*;import android.database.sqlite.*;import java.util.*;import org.json.*;

final class TrackingDatabase extends SQLiteOpenHelper {
    static final Object NO_PREVIOUS = new Object();
    TrackingDatabase(Context context) { super(context, "tracking.sqlite", null, 1); }
    public void onCreate(SQLiteDatabase db) {
        db.execSQL("CREATE TABLE trackers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,description TEXT,createdAt INTEGER NOT NULL,updatedAt INTEGER NOT NULL)");
        db.execSQL("CREATE TABLE items(id INTEGER PRIMARY KEY AUTOINCREMENT,trackerId INTEGER NOT NULL,title TEXT NOT NULL,sortOrder INTEGER NOT NULL,FOREIGN KEY(trackerId) REFERENCES trackers(id) ON DELETE CASCADE)");
        db.execSQL("CREATE TABLE fields(id INTEGER PRIMARY KEY AUTOINCREMENT,itemId INTEGER NOT NULL,fieldKey TEXT NOT NULL,label TEXT NOT NULL,type TEXT NOT NULL,sortOrder INTEGER NOT NULL,defaultValue TEXT,incrementValue REAL,decimals INTEGER,unit TEXT,required INTEGER NOT NULL,prefillFromPrevious INTEGER NOT NULL,FOREIGN KEY(itemId) REFERENCES items(id) ON DELETE CASCADE)");
        db.execSQL("CREATE TABLE sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,trackerId INTEGER NOT NULL,createdAt INTEGER NOT NULL,updatedAt INTEGER NOT NULL,status TEXT NOT NULL CHECK(status IN ('open','completed')),FOREIGN KEY(trackerId) REFERENCES trackers(id))");
        db.execSQL("CREATE TABLE item_records(id INTEGER PRIMARY KEY AUTOINCREMENT,sessionId INTEGER NOT NULL,trackerId INTEGER NOT NULL,itemId INTEGER NOT NULL,valuesJson TEXT NOT NULL,createdAt INTEGER NOT NULL,updatedAt INTEGER NOT NULL,UNIQUE(sessionId,itemId),FOREIGN KEY(sessionId) REFERENCES sessions(id),FOREIGN KEY(itemId) REFERENCES items(id))");
        seed(db);
    }
    public void onUpgrade(SQLiteDatabase db,int oldVersion,int newVersion) {}
    private long now(){return System.currentTimeMillis();}
    private void seed(SQLiteDatabase db){ long t=insertTracker(db,"Training","Beispiel-Tracker"); long p1=insertItem(db,t,"Klimmzug 1",0); field(db,p1,"reps","Wiederholungen","int",0,"8",1,0,"",true); field(db,p1,"weight","Zusatzgewicht","float",1,"0",2.5,1,"kg",true); field(db,p1,"note","Notiz","string",2,"",1,0,"",false); long p2=insertItem(db,t,"Plank",1); field(db,p2,"duration","Dauer","duration",0,"60000",1,0,"",true); field(db,p2,"note","Notiz","string",1,"",1,0,"",false); }
    long insertTracker(SQLiteDatabase db,String name,String desc){ContentValues v=new ContentValues();long n=now();v.put("name",name);v.put("description",desc);v.put("createdAt",n);v.put("updatedAt",n);return db.insert("trackers",null,v);} long insertItem(SQLiteDatabase db,long tid,String title,int order){ContentValues v=new ContentValues();v.put("trackerId",tid);v.put("title",title);v.put("sortOrder",order);return db.insert("items",null,v);} void field(SQLiteDatabase db,long item,String key,String label,String type,int order,String def,double inc,int dec,String unit,boolean pre){ContentValues v=new ContentValues();v.put("itemId",item);v.put("fieldKey",key);v.put("label",label);v.put("type",type);v.put("sortOrder",order);v.put("defaultValue",def);v.put("incrementValue",inc);v.put("decimals",dec);v.put("unit",unit);v.put("required",0);v.put("prefillFromPrevious",pre?1:0);db.insert("fields",null,v);} 
    List<Tracker> trackers(){SQLiteDatabase db=getReadableDatabase();List<Tracker> list=new ArrayList<>();Cursor c=db.rawQuery("SELECT * FROM trackers ORDER BY updatedAt DESC",null);while(c.moveToNext())list.add(readTracker(db,c.getLong(0)));c.close();return list;}
    Tracker readTracker(long id){return readTracker(getReadableDatabase(),id);} Tracker readTracker(SQLiteDatabase db,long id){Cursor c=db.rawQuery("SELECT id,name,description,createdAt,updatedAt FROM trackers WHERE id=?",new String[]{""+id}); if(!c.moveToFirst()){c.close();return null;} Tracker t=new Tracker();t.id=c.getLong(0);t.name=c.getString(1);t.description=c.getString(2);t.createdAt=c.getLong(3);t.updatedAt=c.getLong(4);c.close();Cursor i=db.rawQuery("SELECT id,title,sortOrder FROM items WHERE trackerId=? ORDER BY sortOrder,id",new String[]{""+id});while(i.moveToNext()){Item item=new Item();item.id=i.getLong(0);item.trackerId=id;item.title=i.getString(1);item.order=i.getInt(2);Cursor f=db.rawQuery("SELECT id,fieldKey,label,type,sortOrder,defaultValue,incrementValue,decimals,unit,required,prefillFromPrevious FROM fields WHERE itemId=? ORDER BY sortOrder,id",new String[]{""+item.id});while(f.moveToNext()){FieldDefinition d=new FieldDefinition();d.id=f.getLong(0);d.itemId=item.id;d.key=f.getString(1);d.label=f.getString(2);d.type=f.getString(3);d.order=f.getInt(4);d.defaultValue=f.getString(5);d.increment=f.getDouble(6);d.decimals=f.getInt(7);d.unit=f.getString(8);d.required=f.getInt(9)==1;d.prefillFromPrevious=f.getInt(10)==1;item.fields.add(d);}f.close();t.items.add(item);}i.close();return t;}
    List<Session> sessions(){List<Session> s=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT id,trackerId,createdAt,updatedAt,status FROM sessions ORDER BY createdAt DESC",null);while(c.moveToNext()){Session x=new Session();x.id=c.getLong(0);x.trackerId=c.getLong(1);x.createdAt=c.getLong(2);x.updatedAt=c.getLong(3);x.status=c.getString(4);s.add(x);}c.close();return s;}
    Session session(long id){Cursor c=getReadableDatabase().rawQuery("SELECT id,trackerId,createdAt,updatedAt,status FROM sessions WHERE id=?",new String[]{""+id});c.moveToFirst();Session s=new Session();s.id=c.getLong(0);s.trackerId=c.getLong(1);s.createdAt=c.getLong(2);s.updatedAt=c.getLong(3);s.status=c.getString(4);c.close();return s;}
    long createSession(long trackerId){ContentValues v=new ContentValues();long n=now();v.put("trackerId",trackerId);v.put("createdAt",n);v.put("updatedAt",n);v.put("status","open");return getWritableDatabase().insert("sessions",null,v);} void complete(long sid){ContentValues v=new ContentValues();v.put("status","completed");v.put("updatedAt",now());getWritableDatabase().update("sessions",v,"id=?",new String[]{""+sid});}
    Map<Long,ItemRecord> records(long sid){Map<Long,ItemRecord> m=new HashMap<>();Cursor c=getReadableDatabase().rawQuery("SELECT id,sessionId,trackerId,itemId,valuesJson,createdAt,updatedAt FROM item_records WHERE sessionId=?",new String[]{""+sid});while(c.moveToNext()){ItemRecord r=new ItemRecord();r.id=c.getLong(0);r.sessionId=c.getLong(1);r.trackerId=c.getLong(2);r.itemId=c.getLong(3);r.valuesJson=c.getString(4);r.createdAt=c.getLong(5);r.updatedAt=c.getLong(6);m.put(r.itemId,r);}c.close();return m;}
    void saveRecord(Session s,long itemId,Map<String,Object> values){if(!"open".equals(s.status))return;ContentValues v=new ContentValues();long n=now();v.put("sessionId",s.id);v.put("trackerId",s.trackerId);v.put("itemId",itemId);v.put("valuesJson",JsonUtil.stringify(values));v.put("updatedAt",n);v.put("createdAt",n);getWritableDatabase().insertWithOnConflict("item_records",null,v,SQLiteDatabase.CONFLICT_REPLACE);ContentValues u=new ContentValues();u.put("updatedAt",n);getWritableDatabase().update("sessions",u,"id=?",new String[]{""+s.id});}
    Object previousValue(long trackerId,long beforeSessionId,long itemId,String key){Cursor c=getReadableDatabase().rawQuery("SELECT r.valuesJson FROM item_records r JOIN sessions s ON s.id=r.sessionId WHERE r.trackerId=? AND r.itemId=? AND s.id<>? ORDER BY s.createdAt DESC LIMIT 1",new String[]{""+trackerId,""+itemId,""+beforeSessionId});try{if(c.moveToFirst()){JSONObject o=new JSONObject(c.getString(0));return o.has(key)?(o.isNull(key)?null:o.get(key)):NO_PREVIOUS;}return NO_PREVIOUS;}catch(JSONException e){throw new IllegalArgumentException(e);}finally{c.close();}}
    int recordCount(long sid){Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM item_records WHERE sessionId=?",new String[]{""+sid});c.moveToFirst();int n=c.getInt(0);c.close();return n;}
}
